### ISSUE TITLE
Like the ability to define ospf cost in a graphml file.

### ISSUE THREAD

**Issue by robertja52** [sk2/autonetkit#265]
I would like the ability to define ospf cost in a graphml file. I see two possible ways to define it.
1) Allow it to be defined in a broadcast_domain object (switch)
2) All it to be defined on a wire/edge.

The first would be defined the same way as ospf area. The second would allow separate costs per direction if the wires were separated by a switch. Uniform costs in each direction of a wire is common.

In general, any variable that can be seen when hovering over a wire should be definable on the wire or broadcast domain. ospf_cost is just a special case which I can't get working.

**Comment by sk2** [comment]
Yeah, It's hard to map from edges to interfaces. One way is the use of directed arrows, and a convention or pre-processor step then.
Specifying them on the switch would be a bit awkward I think.
