### ISSUE TITLE
Defining ibgp_role disabled causes mako quagga scripts to crash.

### ISSUE THREAD

**Issue by robertja52** [sk2/autonetkit#266]
When I define ibgp_role Disabled on a router node, it causes the quagga mako scripts to crash. The fix is easy. The scripts have the following form

% for obj in bgp.var:
 # use obj
% endfor

If the object bgp.var is not defined it crashes. The fix is to find these and add the following.

% if bgp.var:
% for obj in bgp.var:
 # use obj
% endfor
% endif

**Comment by robertja52** [comment]
[autonetkit.zip](https://github.com/sk2/autonetkit/files/159268/autonetkit.zip)

**Comment by sk2** [comment]
thanks -do you have this in a .diff form?
