### ISSUE TITLE
ank_webserver crashes when choosing ip_allocations.

### ISSUE THREAD

**Issue by robertja52** [sk2/autonetkit#267]
ank_webserver crashes when choosing ip_allocations. This happens even without an input file. The example output crashes when I choose ip_allocations. 

INFO:root:Starting on port 8000 at 2016 03 07_11:17:53
INFO:root:Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0
INFO:root:Rendering template with uuid singleuser
INFO:tornado.access:304 GET / (192.168.3.164) 4.70ms
INFO:tornado.access:304 GET /d3.v3.min.js (192.168.3.164) 5.69ms
INFO:tornado.access:304 GET /jquery-1.7.2.min.js (192.168.3.164) 1.29ms
INFO:tornado.access:304 GET /underscore-min.js (192.168.3.164) 0.91ms
INFO:tornado.access:304 GET /jquery.tipsy.js (192.168.3.164) 0.90ms
INFO:tornado.access:304 GET /jquery.ba-bbq.min.js (192.168.3.164) 0.91ms
INFO:tornado.access:304 GET /colorbrewer.js (192.168.3.164) 1.03ms
INFO:tornado.access:304 GET /font-awesome.min.css (192.168.3.164) 0.90ms
INFO:tornado.access:304 GET /default.css (192.168.3.164) 1.12ms
INFO:tornado.access:304 GET /print.css (192.168.3.164) 0.99ms
INFO:tornado.access:304 GET /ank_render.js (192.168.3.164) 1.17ms
INFO:tornado.access:304 GET /tipsy.css (192.168.3.164) 1.02ms
INFO:tornado.access:304 GET /maximised.css (192.168.3.164) 0.60ms
INFO:root:Client connected from 192.168.3.164
INFO:root:Received message overlay_list from websocket client
INFO:root:Trying for anm list with UUID singleuser
INFO:root:Received message overlay_id=phy from websocket client
INFO:root:Getting overlay phy with UUID singleuser
INFO:root:Trying for anm list with UUID singleuser
INFO:tornado.access:304 GET /icons/router.svg (192.168.3.164) 1.39ms
INFO:root:Received message overlay_id=ip_allocations from websocket client
INFO:root:Getting overlay ip_allocations with UUID singleuser
WARNING:root:Unable to find overlay ip_allocations in topoplogy with UUID singleuser
ERROR:tornado.application:Uncaught exception in /ws
Traceback (most recent call last):
  File "/home/robertja/.local/lib/python2.7/site-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/websocket.py", line 417, in _run_callback
    callback(_args, *_kwargs)
  File "build/bdist.linux-x86_64/egg/autonetkit/webserver.py", line 109, in on_message
    self.update_overlay()
  File "build/bdist.linux-x86_64/egg/autonetkit/webserver.py", line 119, in update_overlay
    self.write_message(body)
  File "/home/robertja/.local/lib/python2.7/site-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/websocket.py", line 218, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/home/robertja/.local/lib/python2.7/site-packages/tornado-4.3-py2.7-linux-x86_64.egg/tornado/websocket.py", line 687, in write_message
    assert isinstance(message, bytes)
AssertionError
INFO:root:Client disconnected from 192.168.3.164

**Comment by sk2** [comment]
Hi, yes IP allocations was removed from the generated json, but doesn't look like it was removed from the webserver.
I'll need to fix that.

**Comment by logik4** [comment]
Hi Sk2,

Do you mean the feature, in the future, will be removed? 

Thanks
